//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sared.Models.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionCliente
    {
        public int ID { get; set; }
        public int idCliente { get; set; }
        public string direccion { get; set; }
        public int idProvincia { get; set; }
        public int idCanton { get; set; }
        public int idDistrito { get; set; }
        public int idTipoDireccion { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual TipoDireccion TipoDireccion { get; set; }
    }
}
