//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sared.Models.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosxPerfil
    {
        public int ID { get; set; }
        public int idPermiso { get; set; }
        public int idPerfil { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Permisos Permisos { get; set; }
    }
}
